version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: "WMF 5"
install:
  - cinst pester
  - cinst PSScriptAnalyzer
environment:
  pwsapikey: b38d7a253c46ef9ad2b8f76439e5c3fe
  pwsgenapikey: b39e2f43a5c8d768cba5629fd3e734ea
  pwsuri: https://devpws01.northeurope.cloudapp.azure.com

build: "off"

test_script:
  - ps: .\build\4.Analyze.ps1
  - ps: $res = Invoke-Pester -Path ".\Functions\" -OutputFormat NUnitXml -OutputFile TestsResults.xml -PassThru
  - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestsResults.xml))
  - ps: if ($res.FailedCount -gt 0) { throw "$($res.FailedCount) tests failed."}
  - ps: .\tests\pester.ps1